version: '3.8'
services:
  user:
    build:
      context: ./user-service
    ports:
      - "5000:5000"
    env_file:
      - ./user-service/.env
    depends_on:
      - db
  product:
    build:
      context: ./product-service
    ports:
      - "3000:3000"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo
  order:
    build:
      context: ./order-service
    ports:
      - "8080:8080"
    env_file:
      - ./order-service/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: productdb
  db_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orderdb
